### ISSUE TITLE
dependencies not encoded in setup.py

### ISSUE THREAD

**Issue by svenevs** [kootenpv/rebrand#2]
Fresh install fails out.  I needed to install the `colorama` and `fire` packages from PyPi before I can even run `rebrand --help` (but there may be others that I already installed).  Or I guess `rebrand -- --help`?  The help strings are kind of confusing ;)

**Comment by kootenpv** [comment]
Thanks a lot for posting this... yea I am not happy with `Fire` actually.... but for now I'll add them to the dependencies at least!

**Comment by MIROPRAV** [comment]
Zerkalo0, [09.02.19 4:45]
setup.py 


Zerkalo0, [09.02.19 4:45]
setup.py
http://setup.py/
https://t.me/HOBOMiR/667

setap.ру ⁿ°′ setap.py :)≠(.· 
{@≠\≠#≠$≠*≠&=§]≈¶÷)€=

меседж ничего не должен:)
пользователь так точно(:
ООООООООООООООООООООООООООООООООООООООООООООООООООООООООО
000000000000000000000000
∅∅∅∅∅∅∅∅∅∅∅∅∅∅∅

**Comment by kootenpv** [comment]
It's using argparser now, so this shouldn't be an issue anymore.
